// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqh502lJKBu4lzJvuTs7CBhLblAIcVmQI',
    appId: '1:37943352105:web:fe50136013a1efe64a7538',
    messagingSenderId: '37943352105',
    projectId: 'trip-assistant-b04f5',
    authDomain: 'trip-assistant-b04f5.firebaseapp.com',
    databaseURL: 'https://trip-assistant-b04f5-default-rtdb.firebaseio.com',
    storageBucket: 'trip-assistant-b04f5.firebasestorage.app',
    measurementId: 'G-FYQHLZSYRN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZvgmfrG9Vlj3tawcCcLQsBkJ-9GFZnzU',
    appId: '1:37943352105:android:e2ad4bc66ae7284e4a7538',
    messagingSenderId: '37943352105',
    projectId: 'trip-assistant-b04f5',
    databaseURL: 'https://trip-assistant-b04f5-default-rtdb.firebaseio.com',
    storageBucket: 'trip-assistant-b04f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyKeZU2_4ktcqQlL7tDNd9nTanfiouDuE',
    appId: '1:37943352105:ios:042cbdef9034b4944a7538',
    messagingSenderId: '37943352105',
    projectId: 'trip-assistant-b04f5',
    databaseURL: 'https://trip-assistant-b04f5-default-rtdb.firebaseio.com',
    storageBucket: 'trip-assistant-b04f5.firebasestorage.app',
    iosBundleId: 'com.example.tripAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyKeZU2_4ktcqQlL7tDNd9nTanfiouDuE',
    appId: '1:37943352105:ios:042cbdef9034b4944a7538',
    messagingSenderId: '37943352105',
    projectId: 'trip-assistant-b04f5',
    databaseURL: 'https://trip-assistant-b04f5-default-rtdb.firebaseio.com',
    storageBucket: 'trip-assistant-b04f5.firebasestorage.app',
    iosBundleId: 'com.example.tripAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqh502lJKBu4lzJvuTs7CBhLblAIcVmQI',
    appId: '1:37943352105:web:7d0d7dceeeed20e94a7538',
    messagingSenderId: '37943352105',
    projectId: 'trip-assistant-b04f5',
    authDomain: 'trip-assistant-b04f5.firebaseapp.com',
    databaseURL: 'https://trip-assistant-b04f5-default-rtdb.firebaseio.com',
    storageBucket: 'trip-assistant-b04f5.firebasestorage.app',
    measurementId: 'G-TTZDNP3JRQ',
  );

}